# Generated by Django 4.1.3 on 2024-09-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_key',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Chave do carrinho'),
        ),
    ]
