# Generated by Django 4.1.3 on 2024-09-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_cartitem_cart_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Chave do carrinho'),
        ),
    ]
